### ISSUE TITLE
Rotas inválidas

### ISSUE THREAD

**Issue by phcamargo23** [vicenteneto/python-cartolafc#30]
Recurso do método `api.get_team({'time'})` não encontrado (404).

**Comment by vicenteneto** [comment]
Sim, a versão deste ano mudou as rotas e ainda estou vendo quais mudaram para atualizar a api.

**Comment by vicenteneto** [comment]
@phcamargo23 

Problema resolvido!
Pode se basear nos exemplos disponíveis no diretório de exemplos.
