### ISSUE TITLE
Fazer os models retornarem JSON

### ISSUE THREAD

**Issue by josecostamartins** [vicenteneto/python-cartolafc#47]
Atualmente todos os models retornam objetos do to tipo Clube, PontuacaoInfo, etc. seria muito bom ser eles imprimissem o valor do objeto em um formato json.

isso pode feito sobrecarregando o método __repr__ de cada model e retornando algo como o descrito aqui: https://stackoverflow.com/questions/7408647/convert-dynamic-python-object-to-json

**Comment by vicenteneto** [comment]
Olá José,

realmente isto era algo que estava faltando. O seu pull request foi aceito e já está integrado na master (#49) e a issue vai ser fechada.

Creio que ainda hoje gerarei uma nova versão no PyPi com este seu fix.

Valeu!!
