### ISSUE TITLE
Installing issue (ascii)

### ISSUE THREAD

**Issue by marxperx** [vicenteneto/python-cartolafc#53]
Sei que o Cartola deve interessar principalmente a brasileiros, normalmente com o python preparado para lidar com o Unicode, mas tentei instalar num note com configuracoes us, e o arquivo README fez travar o script com o erro ascii 128. Quando apaguei os caracteres especiais, o script funcionou. E um pequeno bug, mas talvez corrigi-lo facilite instala-lo em todos os computadores.

Edit: Muito bom modulo. Mandou muito bem.

**Comment by vicenteneto** [comment]
Opa @marxperx!

Por favor, voce poderia testar utilizando a versao 1.4.20?

**Comment by vicenteneto** [comment]
Acabei de lançar a versao 1.4.21, e nos meus testes deu certo.
Me avisa o resultado, por favor. :)

**Comment by marxperx** [comment]
Funcionou perfeitamente num computador sem preparacao para unicode! Abs!
