### ISSUE TITLE
api.time falha quando jogador/tecnico sem clube

### ISSUE THREAD

**Issue by itsreallythatsimple** [vicenteneto/python-cartolafc#69]
O problema está em models.py, linha 98.
clube = clubes[data['clube_id']]

Quando um treinador é demitido, por exemplo, seu clube_id é 1.
Nao há nenhum clube com id=1 em data, entao ocorre um KeyError.

Minha sugestao é fazer:
clube = clubes[data['clube_id']] if data['clube_id'] != 1 else "Sem Clube"

Abs,
Leandro

**Comment by vicenteneto** [comment]
Resolvido na última versao em dev.
