### ISSUE TITLE
Erro ao tentar utilizar a função "mercado"

### ISSUE THREAD

**Issue by henrique1996n1** [vicenteneto/python-cartolafc#73]
Segui os tutoriais corretamente e ao tentar utilizar a função "mercado", o seguinte erro me é retornado:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-80-64cafe56e1e0> in <module>
----> 1 teste=api.mercado()
      2 teste

~\anaconda3\lib\site-packages\cartolafc\api.py in mercado(self)
    212     def mercado(self) -> Mercado:
    213         """ Obtém o status do mercado na rodada atual.
--> 214 
    215         Returns:
    216             Uma instância de cartolafc.Mercado representando o status do mercado na rodada atual.

~\anaconda3\lib\site-packages\cartolafc\models.py in from_dict(cls, data)
    137         times = [TimeInfo.from_dict(time, ranking=ranking) for time in data['times']] if 'times' in data else None
    138         return cls(data_liga['liga_id'], data_liga['nome'], data_liga['slug'], data_liga['descricao'], times)
--> 139 
    140 
    141 class LigaPatrocinador(BaseModel):

KeyError: 'aviso'

Não sei mais o que fazer. Agradeço muito se puderem responder por favor. Obrigado

**Comment by vicenteneto** [comment]
Valeu! Ja foi resolvido na ultima versao em dev
