### ISSUE TITLE
Api.Time() parou de funcionar - ausência de clubes

### ISSUE THREAD

**Issue by aebrag** [vicenteneto/python-cartolafc#77]
O Cartola FC retirou da api de time/rodada (salientado em amarelo) a parte de clubes, o que fez com que a Api.Time() deixasse de funcionar exatamente no ponto abaixo destacado pela seta em vermelho. Alguém sabe uma maneira elegante de contornar a situação?

![image](https://user-images.githubusercontent.com/43657049/134602970-7149b587-e2fe-47e4-8600-7566e72beb76.png)

Contornei chamando uma outra api apenas para pegar os clubes, mas confesso que não é a melhor maneira de fazer isso, mas estava com pressa para resolver o fechamento da rodada e foi assim mesmo. Se alguém tiver uma ideia mais elegante e puder contribuir, agradeço.

![image](https://user-images.githubusercontent.com/43657049/134603190-a975c115-a50b-474c-bb97-8dfdf56fb6aa.png)

**Comment by diegobarpereira** [comment]
Caro @aebrag no meu eu resolvi assim:
clubes = {clube['id']: Clube.from_dict(clube) for clube in data['clubes'].values()} if 'clubes' in data else Api().clubes()

Se ta correto? Nao sei. Funciona? Sim.

**Comment by vicenteneto** [comment]
A última versao em `dev` obtém os clubes utilizando a API de clubes. Obrigado a desculpa pela demora 😬
